name: Android Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcursor-dev libxi-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev openjdk-17-jdk
      - name: Install v tools
        run: |
          v install vab
          v run ~/.vmodules/vab/vab.v install ndk
          yes | sdkmanager "platforms;android-29"
          sed -i 's/-cc clang/-cc gcc/g' ~/.vmodules/vab/android/compile.v
      - name: Build Android APK
        run: v run ~/.vmodules/vab/vab.v mclike.v -o mclike.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mclike-android
          path: mclike.apk
